deployment:
  tasks:
    - export DEPLOYPATH=/home/rosasuy/reserva-server/
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - cd $DEPLOYPATH && npm install --omit=dev
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
